Example run changes directory to repository root
CDCgov/DynODE pull request #289
Opened 2024-10-24 22:15 UTC by edbaskerville

The example depends on being run in the root directory of the repo.

This minimal change simply does a `cd` into the root directory of the repo. A longer-term conversation: how do paths work relative to scripts, config files, etc., etc.? Best not to change anything significant until the reproducibility model stabilizes.

Also modified path computations to use `os.path.join()`.

2024-10-24 22:43 UTC, arik-shurygin requested changes

2024-10-24 22:43 UTC, arik-shurygin commented on examples/example_end_to_end_run.py
> +# the different segments of code responsible for running the model
This causes the file to fail pre-commit checks: `E402 Module level import not at top of file`. You have two solutions, either add the following command: `# ruff: noqa: E402` to disable the particular pre-commit check. Or move the lines below the import. I suggest the latter unless you have a good reason to keep the current ordering

2024-10-25 15:56 UTC, edbaskerville commented
I'll take a look at this on Monday.

2024-10-29 15:42 UTC, edbaskerville commented
I think it probably makes sense to punt this kind of thing until after the packages get reorg'd and relative paths get re-thought.

At that point we can identify the best non-hacky solution—I suspect there's a "correct" way to do this that doesn't involve messing with the python search path at runtime.

2024-10-29 15:42 UTC, closed without merging